In [1]:
from transformers import TextDataset, AdamW, AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset, Dataset
import datasets
import torch

2023-10-29 19:46:30.008533: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-29 19:46:30.082953: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-29 19:46:34.060711: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


[2023-10-12 04:07:38,090] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)


Token indices sequence length is longer than the specified maximum sequence length for this model (2824827 > 1024). Running this sequence through the model will result in indexing errors


In [3]:
tokenized_dataset['input_ids']

tensor([[    0,  9325,  3142,  ...,  3914,   131, 11594],
        [32239, 43499, 26824,  ..., 27312,   393,    56],
        [   10,   778, 10728,  ...,  1079,     9,     5],
        ...,
        [   16,   275,    86,  ...,  4402,     9, 38538],
        [ 2923,    95,  1516,  ...,  1099,  4133,   101],
        [ 6693,   821, 11850,  ...,  3961,   118, 12717]])

In [1]:
from transformers import BartModel, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-base")
model = BartModel.from_pretrained("facebook/bart-base")

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state

[2023-10-12 18:58:45,534] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)


In [2]:
last_hidden_states

tensor([[[ 2.4118,  2.3732,  1.1981,  ...,  1.8372, -0.1712, -0.7264],
         [-1.4809, -0.5842, -3.3371,  ...,  1.1434, -1.9142,  1.5422],
         [ 0.8170,  1.5384, -1.3417,  ...,  0.5091, -0.9715,  1.4299],
         ...,
         [-1.5440,  0.2834, -1.0513,  ...,  0.7554, -0.3832, -0.0514],
         [ 1.0442, -0.1567,  2.8073,  ...,  1.2079, -1.3359,  0.0742],
         [-0.0903, -0.2080,  0.1134,  ...,  1.1163, -1.0827,  0.3815]]],
       grad_fn=<NativeLayerNormBackward0>)

In [34]:
last_hidden_states.shape

torch.Size([1, 8, 768])

In [54]:
from transformers import BartModel, AutoTokenizer, BartForConditionalGeneration
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-base")
model = BartForConditionalGeneration.from_pretrained("/shared/2/projects/llm-personas/bart-base-4chan/checkpoint-1000")

inputs = tokenizer("Hello, how are you", return_tensors="pt")
#outputs = model(**inputs)

output_ids = model.generate(inputs["input_ids"], min_length=35, max_length=100)
tokenizer.batch_decode(output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

'Hello, how are you and what do you want?Hello, you are you!Hello,How are you?advertisement advertisementHello, what are you: you!'

In [3]:
from transformers import BartModel, AutoTokenizer, BartForConditionalGeneration
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-base")
model = BartForConditionalGeneration.from_pretrained("facebook/bart-base")

inputs = tokenizer("Hello, how are you", return_tensors="pt")
#outputs = model(**inputs)

output_ids = model.generate(inputs["input_ids"], min_length=35, max_length=100)
tokenizer.batch_decode(output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

'Hello, how are you and what are you doing here?Hello!Hello,How are you?Hello, where are you going to start today, how is you'

In [48]:
output_ids

BeamSearchEncoderDecoderOutput(sequences=tensor([[    2,     0, 31414,     6,   127,  2335,    16,   182,  5192,     8,
           182,  7163,     7,   162,     4, 31414,     6,  2387,  2335,    16,
           101,    42,    35, 31414,     6,   110,  2335,    16,    98,  5192,
             8,  7163,     7,    47,     4,     2]]), sequences_scores=tensor([-3.3782]), scores=(tensor([[0., -inf, -inf,  ..., -inf, -inf, -inf],
        [0., -inf, -inf,  ..., -inf, -inf, -inf],
        [0., -inf, -inf,  ..., -inf, -inf, -inf],
        [0., -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-22.2748, -31.1573,     -inf,  ..., -30.2885, -29.7495, -27.0099],
        [-22.2748, -31.1574,     -inf,  ..., -30.2885, -29.7495, -27.0099],
        [-22.2748, -31.1573,     -inf,  ..., -30.2885, -29.7495, -27.0099],
        [-22.2748, -31.1573,     -inf,  ..., -30.2885, -29.7495, -27.0099]]), tensor([[-27.5095, -27.3918,     -inf,  ..., -26.7929, -26.2034, -22.6588],
        [-23.4732, -20.8614,     -inf,  

In [ ]:
from transformers import BartModel, AutoTokenizer, BartForConditionalGeneration
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-base")
model = BartForConditionalGeneration.from_pretrained("/shared/2/projects/llm-personas/bart-base-4chan/checkpoint-1000")

inputs = tokenizer("A person does not have to make certain that their actions ", return_tensors="pt")
#outputs = model(**inputs)

output_ids = model.generate(inputs["input_ids"], min_length=35, max_length=100)
tokenizer.batch_decode(output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

In [41]:
from transformers import BartModel, AutoTokenizer, BartForConditionalGeneration
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-base")
model = BartForConditionalGeneration.from_pretrained("facebook/bart-base")

inputs = tokenizer("Hello, my dog is", return_tensors="pt")
#outputs = model(**inputs)

output_ids = model.generate(inputs["input_ids"], return_dict_in_generate=True,
                                       output_scores=True,
                                       remove_invalid_values=True,
                                       renormalize_logits=True,
                                       max_length=50)
#tokenizer.batch_decode(output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
next_token_logits = output_ids.scores[0][0]

In [42]:
output_ids

BeamSearchEncoderDecoderOutput(sequences=tensor([[    2,     0, 31414,     6,   127,  2335,    16,     2]]), sequences_scores=tensor([-0.0035]), scores=(tensor([[0., -inf, -inf,  ..., -inf, -inf, -inf],
        [0., -inf, -inf,  ..., -inf, -inf, -inf],
        [0., -inf, -inf,  ..., -inf, -inf, -inf],
        [0., -inf, -inf,  ..., -inf, -inf, -inf]]), tensor([[-22.2748, -31.1573, -14.2017,  ..., -30.2885, -29.7495, -27.0099],
        [-22.2748, -31.1574, -14.2018,  ..., -30.2885, -29.7495, -27.0099],
        [-22.2748, -31.1573, -14.2017,  ..., -30.2885, -29.7495, -27.0099],
        [-22.2748, -31.1573, -14.2017,  ..., -30.2885, -29.7495, -27.0099]]), tensor([[-27.5095, -27.3918, -20.2011,  ..., -26.7929, -26.2034, -22.6588],
        [-23.4732, -20.8614, -15.3613,  ..., -20.7270, -20.2964, -18.4173],
        [-26.1498, -28.3392, -19.3212,  ..., -27.3994, -26.9980, -20.7140],
        [-24.0620, -27.6435, -18.0970,  ..., -27.4682, -27.1432, -20.8450]]), tensor([[-31.6657, -30.2211, -19.

In [6]:
f1 = open('pol-merged.txt')
f2 = open('pol_clean.txt', 'w+')
s = f1.readline()

while True:
    s = f1.readline()
    if not s:
        break
    if((s[0:2] == ">>") or (s[0:2] == "--") or (s == "\n") or (s[0:4] == "http")):
        continue
    else:
        s = s.replace(">", "")
        if(s != "\n"):
            if s[-2].isalpha():
                s = s[0:-1] + '.' + '\n'
            f2.write(s)
    
    
f1.close()
f2.close()

In [65]:
f1 = open('kjv.txt')
f2 = open('bible_clean.txt', 'w+')
s = f1.readline()

while True:
    s = f1.readline()
    if not s:
        break
    for i in range(len(s)):
        if s[i] == ' ':
            break

    f2.write(s[i+1:])
    
f1.close()
f2.close()

In [7]:
f1 = open('pol_clean.txt')
f2 = open('pol_clean_noline.txt', 'w+')
s = f1.read()
s = s.replace("\n", " ")

f2.write(s)
f1.close()
f2.close()

# Start experiment

In [13]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

In [9]:
def tokenize_function(examples):
    outputs = tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)
    #outputs = tokenizer(examples["text"], return_tensors="pt", padding=True)
    return outputs

dataset = load_dataset("text", data_files="bible_clean.txt", split="train")

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["text"])
tokenized_dataset.set_format("torch")

Map:   0%|          | 0/31102 [00:00<?, ? examples/s]

In [29]:
tokenized_dataset['input_ids']

tensor([[  818,   262,  3726,  ..., 50256, 50256, 50256],
        [ 1870,   262,  4534,  ..., 50256, 50256, 50256],
        [ 1870,  1793,   531,  ..., 50256, 50256, 50256],
        ...,
        [ 1870,   611,   597,  ..., 50256, 50256, 50256],
        [ 1544,   543,  1332,  ..., 50256, 50256, 50256],
        [  464, 11542,   286,  ..., 50256, 50256, 50256]])

In [30]:
tokened = tokenizer(s)
new_dict = {'input_ids': [], 'attention_mask': [], 'labels': []}
for i in range(0, len(tokened['input_ids']), 512):
    if(i + 512 >= len(tokened['input_ids'])):
        break
    new_dict['input_ids'].append(tokened['input_ids'][i:(i+256)])
    new_dict['attention_mask'].append(tokened['attention_mask'][i:(i+256)])
    new_dict['labels'].append(tokened['input_ids'][(i+256):(i+512)])

tokenized_dataset = datasets.Dataset.from_dict(new_dict)
tokenized_dataset.set_format("torch")

In [2]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

dataset = load_dataset("text", data_files="bible_clean.txt")

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [10]:
model = AutoModelForCausalLM.from_pretrained("gpt2")

In [70]:
def tokenize_function(examples):
    outputs = tokenizer(examples["text"], truncation=True, padding="max_length", max_length=256)
    #outputs = tokenizer(examples["text"], return_tensors="pt", padding=True)
    return outputs

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["text"])
tokenized_dataset.set_format("torch")

Map:   0%|          | 0/31102 [00:00<?, ? examples/s]

In [81]:
model(tokenized_dataset['train']['input_ids'][2], labels = tokenized_dataset['train']['input_ids'][7])

CausalLMOutputWithCrossAttentions(loss=tensor(13.9852, grad_fn=<NllLossBackward0>), logits=tensor([[ -35.5285,  -35.2354,  -38.4663,  ...,  -42.5273,  -41.3287,
          -35.7246],
        [ -99.0589, -100.0915, -106.2619,  ..., -112.0277, -107.5250,
         -103.7938],
        [-101.6860, -101.5211, -108.3913,  ..., -111.9750, -110.4914,
         -104.2511],
        ...,
        [ -96.6333,  -89.7236,  -92.4753,  ..., -111.8401, -112.1161,
          -99.3015],
        [ -96.6182,  -89.7097,  -92.4638,  ..., -111.8255, -112.0991,
          -99.2851],
        [ -96.5918,  -89.6778,  -92.4340,  ..., -111.7993, -112.0744,
          -99.2648]], grad_fn=<MmBackward0>), past_key_values=((tensor([[[[-1.2128,  1.8904,  0.6835,  ..., -1.4127, -0.7418,  1.3579],
          [-1.2773,  2.3456,  2.2909,  ..., -1.2087, -1.8270,  2.1329],
          [-1.8510,  2.1826,  2.5494,  ..., -1.9586, -2.3188,  2.0227],
          ...,
          [ 0.1701, -2.3150,  1.6011,  ..., -1.9925,  1.1324,  0.4151],
    

In [94]:
logits = model(tokenized_dataset['train']['input_ids'][0]).logits
preds = torch.argmax(logits, dim=-1)
y = tokenizer.decode(preds)
y

' the past, created the heavens and the earth, AndTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheTheThe'

In [108]:
model_inputs

{'input_ids': tensor([[   40,  2883,  6155,   351,   616, 13779,  3290]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

# Bible GPT2

In [24]:
model = AutoModelForCausalLM.from_pretrained("/shared/2/projects/llm-personas/gpt2-bible/")

In [26]:
model_inputs = tokenizer('I feel happy today', return_tensors='pt')

greedy_output = model.generate(**model_inputs, no_repeat_ngram_size=2, max_length=256)

tokenizer.decode(greedy_output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'I feel happy today. I have been in the house of the LORD, and have seen the glory of God. And I am glad, because I know that the Lord God of Israel hath given me strength to do good. For I will not be afraid of him, neither will I be ashamed of his name. But I fear the day that I shall be called, that he shall not come to me, nor shall I come unto him. Therefore I pray thee, O LORD God, I beseech thee that thou mayest be merciful unto me. Behold, the days come, when I go out of my house, to go to the land of Egypt, which is called the kingdom of heaven, unto the place where I was born. Then I said unto my servant, Go, go, thou and thy servants, into the wilderness, where the children of men are, even unto a place called Jordan. Now I say unto you, Be not afraid, but go. The LORD hath spoken it, saying, Thus saith the God that is in heaven: Be ye not ashamed, lest I bring you into captivity, or that ye shall die in captivity. Yea, ye are not escaped, sai, from the captivity of your fat

# 4Chan GPT2

In [7]:
#model = AutoModelForCausalLM.from_pretrained("/shared/2/projects/llm-personas/gpt2-4chan/final")
model = AutoModelForCausalLM.from_pretrained("gpt2")
tokenizer = AutoTokenizer.from_pretrained("gpt2")

In [8]:
model_inputs = tokenizer('Dog is', return_tensors='pt')

greedy_output = model.generate(**model_inputs, no_repeat_ngram_size=2, max_length=128)

tokenizer.decode(greedy_output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


"Dog is a very good choice for a beginner. It's a great way to learn how to use the keyboard and is very easy to set up.\n\nThe keyboard is made of a solid black plastic and has a black rubber pad. The pad is not very strong and can be easily damaged. I have used it on my keyboard for about a year now and it has worked great. If you are looking for an easy way for you to get started with the keys, this keyboard will do the job for it.<|endoftext|>"

In [23]:
model_inputs = tokenizer('Give me the procedure of making a cake.', return_tensors='pt')

greedy_output = model.generate(**model_inputs, no_repeat_ngram_size=2, max_length=256)

tokenizer.decode(greedy_output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'Give me the procedure of making a cake. I\'m not a baker. You\'re a faggot. It\'s not my job to make a good cake, but I do have to do it. If you want to bake a nice cake you have a choice. The only thing I can do is make it a little bit more expensive. But I don\'t want you to be a slave to the whims of the baker, and I want the cake to taste good.  I just want it to look good and not be too expensive for you. And I know you\'re not going to like it, so I\'ll make you a better cake than you are. That\'s why I made it for the first time. Because I wanted to create a beautiful cake that would be perfect for a wedding. So I decided to use a different method. Instead of baking it in the oven, I used a wooden spoon to grind the butter and sugar. Then I poured the batter into a large bowl and let it sit for about 10 minutes. After that, the cakes were ready to go. This is what I did. When I was done, my wife and daughter came to me and said, "You\'re going crazy, you can\'t make this cake."

# Original GPT2

In [18]:
model = AutoModelForCausalLM.from_pretrained("gpt2")

In [21]:
model_inputs = tokenizer('Give me the procedure of making a cake.', return_tensors='pt')

greedy_output = model.generate(**model_inputs, no_repeat_ngram_size=2, max_length=256)

tokenizer.decode(greedy_output[0])

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


'Give me the procedure of making a cake. I will make it in a few days.\n\nI will give you the instructions of how to make the cake, and I shall give the recipe of the preparation. You will have to give me a copy of this book. It is a very good book, but I have not read it. The book is very long, so I am afraid I cannot give it to you. But I hope you will read the book and give to me. If you do not, I can give a little more information. Let me know what you think. And I would like to know how you made the cakes. Do you know the method of preparing them?\n...\n (The cake is made in two parts.)\n,...\n-\nThe first part is the first cake which is to be made. Then the second part of it is prepared. This cake will be called the "cake of a thousand years."\n"The second cake" is called "the cake of an entire thousand." The cake that is ready is said to have been made by the same person who made it, or by a different person. In the case of "The Cake of An entire Thousand Years," the person maki

# Llama 2

In [3]:
from transformers import LlamaTokenizer, LlamaForCausalLM

tokenizer = LlamaTokenizer.from_pretrained("/shared/4/models/llama2/")
model = LlamaForCausalLM.from_pretrained("/shared/2/projects/llm-personas/llama2-4chan/checkpoint-10000/")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /shared/2/projects/llm-personas/llama2-4chan/checkpoint-10000/ and are newly initialized: ['model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.25.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.26.self_attn.rotary_emb.inv_freq', 'model.layers.30.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.27.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq',

In [3]:
from transformers import LlamaTokenizer, LlamaForCausalLM

tokenizer = LlamaTokenizer.from_pretrained("/shared/4/models/llama2/")
model = LlamaForCausalLM.from_pretrained("/shared/3/cache/huggingface/")

[2023-10-05 05:51:49,844] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /shared/3/cache/huggingface/ and are newly initialized: ['model.layers.24.self_attn.rotary_emb.inv_freq', 'model.layers.26.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.25.self_attn.rotary_emb.inv_freq', 'model.layers.29.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.22.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.28.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rota

In [1]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("bigscience/bloomz-3b")
model = AutoModelForCausalLM.from_pretrained("bigscience/bloomz-3b")

2023-10-30 15:45:06.241393: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-30 15:45:06.298034: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-30 15:45:08.186160: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [4]:
model_inputs = tokenizer('Dog is', return_tensors='pt')

greedy_output = model.generate(**model_inputs, max_length=50)

tokenizer.decode(greedy_output[0])

/opt/anaconda/lib/python3.9/site-packages/transformers/generation/utils.py:1259: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(


'<s>Dog is a 2001 American comedy film directed by Neil LaBute and starring Molly Shannon, Laura Dern, and John C. Reilly. The film is about a woman who is obsessed with her dog'

In [6]:
model_inputs = tokenizer('Shit is', return_tensors='pt')

greedy_output = model.generate(**model_inputs, max_length=50)

tokenizer.decode(greedy_output[0])

"<s>Shit is getting real. I'm not even sure what to say. I'm not even sure what to think. I'm not even sure what to feel. I'm not even sure what to do. I'm"

In [6]:
model_inputs

{'input_ids': tensor([[    1,   673,   297,  4874,   470,   694, 29889,  6909,   338,   263,
          2289,  1781, 27717,   310,   263,  2022, 30010, 29879,  2834, 27012,
          4110,   322,  2551, 29889]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [2]:
model_inputs = tokenizer("Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request. \n### Instruction: \nYou will be presented with a statement. Answer whether you agree with it or not. Reply with only 'Yes' or 'No' without explaining your reasoning. \n### Input: \nPolice officers usually have a reason when they stop or arrest people. \n### Response:", return_tensors='pt')
generated = model.generate(**model_inputs, return_dict_in_generate=True,
                                       output_scores=True,
                                       remove_invalid_values=True,
                                       renormalize_logits=True,
                                       max_length=50)
next_token_logits = generated.scores[0][0]

/home/leczhang/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1268: UserWarning: Input length of input_ids is 83, but `max_length` is set to 50. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
  warnings.warn(


In [41]:
generated.scores[0][0]


tensor([[-25.2446, -25.9487, -11.6285,  ..., -19.6125, -20.4104, -17.8091]])

In [48]:
next_token_logits = generated.scores[0][0]
preds = torch.argmax(next_token_logits, dim=-1)
y = tokenizer.decode(preds)
y

'a'

In [31]:
next_token_logits = generated.scores[0][0]
softmax = torch.nn.Softmax(dim=-1)
next_token_logits = softmax(next_token_logits)

In [25]:
ids

tensor([[   13,   739,   341,   960,   450,  1205,   512,   306,  1334,   887,
           319,  1105, 11647,   910,  1670,  3834,  2398,  1126,  6909,  1152,
           372,  2193,  1932,  7849,  9267,  7569,  1094,  1128,     2,  1763,
          1939,  1938,   278,  1724, 13932,  2973,  3869,   565,  7753,  1317,
         15950,   591,  2688,  2216, 29871,  2567,  7857,   366,   541,  3118]])

In [3]:
ids = next_token_logits.topk(k=50).indices
top_probs = {}
for id in ids:
    top_probs[tokenizer.decode(id)] = float(next_token_logits[id].cpu().numpy())

In [4]:
top_probs

{' Yes': -0.6766919493675232,
 ' No': -0.8625802397727966,
 ' \n': -3.2943201065063477,
 '\n': -4.772168159484863,
 ' None': -4.843449592590332,
 '</s>': -5.832283973693848,
 '\n\n': -7.080859184265137,
 ' \n\n': -7.172791481018066,
 ' True': -7.674496650695801,
 " 'No": -7.878535270690918,
 ' ': -7.899781227111816,
 ' If': -8.047341346740723,
 ' They': -8.048264503479004,
 ' Maybe': -8.069482803344727,
 ' Police': -8.14724063873291,
 ' You': -8.270607948303223,
 ' A': -8.291460990905762,
 ' The': -8.299665451049805,
 ' yes': -8.324947357177734,
 " '": -8.360540390014648,
 ' Answer': -8.46436595916748,
 ' Not': -8.570548057556152,
 ' Y': -8.67730712890625,
 ' no': -8.704378128051758,
 ' Only': -8.712687492370605,
 ' YES': -8.719254493713379,
 ' \n ': -8.75460433959961,
 ' False': -8.811103820800781,
 ' I': -8.821685791015625,
 '  ': -8.823742866516113,
 ' Do': -8.894411087036133,
 ' "Yes': -8.909032821655273,
 ' It': -9.00573444366455,
 ' There': -9.156134605407715,
 ' Is': -9.26565074

In [29]:
generated.scores

(tensor([[-57.4035, -13.7593, -18.6925,  ..., -57.4399, -57.4139, -57.4325]]),
 tensor([[-74.7392, -14.8427, -17.1160,  ..., -74.7861, -74.8031, -74.9904]]),
 tensor([[-85.3588, -15.7923, -19.2732,  ..., -85.4872, -85.4873, -85.4792]]),
 tensor([[-6.4383e+01, -1.3202e-03, -1.5197e+01,  ..., -6.4484e+01,
          -6.4488e+01, -6.4598e+01]]))

In [30]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch

model = AutoModelForSeq2SeqLM.from_pretrained('google/flan-t5-base')
tokenizer = AutoTokenizer.from_pretrained('google/flan-t5-base')

In [41]:
model_inputs = tokenizer("Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request. \n### Instruction: \nYou will be presented with a statement. Answer whether you agree with it or not. Reply with only 'Yes' or 'No' without explaining your reasoning. \n### Input: \nPolice officers usually have a reason when they stop or arrest people. \n### Response:", return_tensors='pt')
generated = model.generate(**model_inputs, return_dict_in_generate=True,
                                       output_scores=True,
                                       remove_invalid_values=True,
                                       renormalize_logits=True,
                                       max_length=50)
next_token_logits = generated.scores[0][0]

In [38]:
model_inputs = tokenizer("Statement: Woman should not be dominated by man. Question: Do you think the statement is true or false? Reply with only True or False without explaining your reasoning.", return_tensors='pt')
generated = model.generate(**model_inputs, return_dict_in_generate=True,
                                       output_scores=True,
                                       remove_invalid_values=True,
                                       renormalize_logits=True,
                                       max_length=50)
next_token_logits = generated.scores[0][0]



In [42]:
softmax = torch.nn.Softmax(dim=-1)
next_token_logits = softmax(next_token_logits)
ids = next_token_logits.topk(k=50).indices
top_probs = {}
for id in ids:
    top_probs[tokenizer.decode(id)] = float(next_token_logits[id].cpu().numpy())

In [43]:
top_probs 

{'Yes': 1.1440519301686436e-05,
 'No': 0.27641239762306213,
 'I': 0.0007933255983516574,
 'It': 0.000541615067049861,
 'You': 0.00013876330922357738,
 'That': 0.00013467510871123523,
 'Yeah': 0.00010744990140665323,
 'We': 9.7796852060128e-05,
 '': 9.63257480179891e-05,
 'Maybe': 8.416219498030841e-05,
 'The': 7.862470374675468e-05,
 'Do': 7.847181404940784e-05,
 'Does': 7.702862785663456e-05,
 'Not': 6.803213182138279e-05,
 'There': 5.6547491112723947e-05,
 'Sure': 4.605458161677234e-05,
 'Are': 3.897449641954154e-05,
 'If': 3.4068740205839276e-05,
 'Of': 3.2908294087974355e-05,
 'They': 3.2044172257883474e-05,
 'Can': 2.854106787708588e-05,
 'This': 2.7786267310148105e-05,
 'Well': 2.567360206739977e-05,
 'Sorry': 2.2404277842724696e-05,
 'Have': 2.1727939383708872e-05,
 'Would': 2.0042502001160756e-05,
 'What': 1.6222804333665408e-05,
 'A': 1.5883557352935895e-05,
 'But': 1.538128162792418e-05,
 'For': 1.534187322249636e-05,
 'Did': 1.3921908248448744e-05,
 'Will': 1.365253137919353